# Generated by Django 3.2.4 on 2021-06-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('capacity', models.CharField(choices=[('ANY', 'Any'), ('1-4', '1-4'), ('5-9', '5-9'), ('10-14', '10-14'), ('15-19', '15-19'), ('20-29', '20-29'), ('30+', '30+')], default='ANY', max_length=8)),
                ('pricing', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
                ('available', models.BooleanField(null=True)),
            ],
        ),
    ]
