# Generated by Django 3.2.4 on 2021-06-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaces',
            name='address',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='spaces',
            name='facilities',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='spaces',
            name='lga',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='spaces',
            name='state',
            field=models.CharField(default='', max_length=64),
        ),
    ]
