# Generated by Django 3.2.4 on 2021-06-28 10:33

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('spaces', '0002_auto_20210623_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaces',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='spaces',
            name='facilities',
        ),
        migrations.AddField(
            model_name='spaces',
            name='facilities',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
