# Generated by Django 3.2.4 on 2021-06-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_auto_20210628_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaces',
            name='available',
            field=models.BooleanField(default='Yes', null=True),
        ),
    ]
