# Generated by Django 3.2.4 on 2021-06-28 10:49

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('spaces', '0005_alter_spaces_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaces',
            name='facilities',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Facilities'),
        ),
    ]
