# Generated by Django 3.2.4 on 2021-06-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_alter_spaces_facilities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spaces',
            options={'verbose_name': 'Space', 'verbose_name_plural': 'Spaces'},
        ),
    ]
