# Generated by Django 3.2.4 on 2021-06-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0007_alter_spaces_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaces',
            name='available',
        ),
        migrations.AddField(
            model_name='spaces',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
