# Generated by Django 3.2.4 on 2021-06-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0009_spaces_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaces',
            name='email',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='spaces',
            name='facebook',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='spaces',
            name='instagram',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='spaces',
            name='twitter',
            field=models.CharField(default='', max_length=64),
        ),
    ]
