# Generated by Django 3.2.4 on 2021-07-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0013_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaces',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
