# Generated by Django 3.2.4 on 2021-07-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0014_alter_spaces_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaces',
            name='capacity',
            field=models.CharField(choices=[('1-4', '1-4'), ('5-9', '5-9'), ('10-14', '10-14'), ('15-19', '15-19'), ('20-29', '20-29'), ('30+', '30+')], default='1-4', max_length=8),
        ),
    ]
